@fashion_store_backend_HostAddress = http://localhost:5109

POST http://localhost:5109/api/FashionStore/GenerateResponse
Content-Type: application/json
X-Timeout-Seconds: 60
{
    "UserPrompt": "Tell me about the features of this blazer.",
    "ProductName": "Navy Single-Breasted Slim Fit Formal Blazer",
    "ProductDescription": "This navy single-breasted slim fit formal blazer is made from a blend of polyester and viscose. It features a notched lapel, a chest welt pocket, two flap pockets, a front button fastening, long sleeves, button cuffs, a double vent to the rear, and a full lining."
}

###
